# action.yml
name: 'Static Code Scan'
description: 'Action for the static code scan'
inputs:
  src_repo:
    description: The name of github source repo to use
    required: true
  scan_tool:
    description: Scan type/tool to run. either 'coverity' or 'clang'
    required: false
    default: 'coverity'
  github_token:
    description: github token
    required: true
  email_token:
    description: Email token.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
  args:
    - ${{ inputs.src_repo }}
    - ${{ inputs.scan_tool }}
